---
#############################################
#              Common vars                  #
#############################################
availability_zone: melbourne-qh2-uom
instance_network: qh2-uom-internal
instance_flavor: uom.mse.2c9g
instance_image: 0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5 # Ubuntu 16.04
instance_key_name: NectarGroup # ssh private key
project_working_directory: /home/xuwang/CCC-COMP90024

#############################################
#             Security group                #
#############################################
security_groups:
  - name: instance2-security-group
    description: "security group for instance2 server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0
  - name: instance3-security-group
    description: "security group for instance3 server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0
  - name: instance4-security-group
    description: "security group for instance4 server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0
  - name: instance1-security-group
    description: "security group for instance1 server"
    rules:
      - name: 'Any'
        protocol: tcp
        port_range_min: 1
        port_range_max: 65535
        remote_ip_prefix: 0.0.0.0/0


#############################################
#                Instance                   #
#############################################
instances:
  - name: instance1
    security_groups: instance1-security-group
    volume_ids: '{{ instance1_volumes|default([]) }}'
    volumes:
      - vol_name: volume_db1
        vol_size: 80
        device: /dev/vdb
        mountpoint: /data
  - name: instance2
    security_groups: instance2-security-group
    volume_ids: '{{ instance2_volumes|default([]) }}'
    volumes:
      - vol_name: volume_db2
        vol_size: 80
        device: /dev/vdb
        mountpoint: /data
  - name: instance3
    security_groups: instance3-security-group
    volume_ids: '{{ instance3_volumes|default([]) }}'
    volumes:
      - vol_name: volume_db3
        vol_size: 80
        device: /dev/vdb
        mountpoint: /data
  - name: instance4
    security_groups: instance4-security-group
    volume_ids: '{{ instance4_volumes|default([]) }}'
    volumes:
      - vol_name: volume_ml
        vol_size: 10
        device: /dev/vdb
        mountpoint: /data
