---
- hosts: dbServers
  vars_files:
    - host_vars/remote_vars.yaml
  gather_facts: true
  roles:
    - role: couchdb-cluster

# - hosts: webServer
#   become: yes
#   vars_files:
#     - host_vars/remote_vars.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-webserver
#     # backend
